### ISSUE TITLE
constructor (double[][] a)

### ISSUE THREAD

**Issue by halvorsenca** [JaysGitLab/cs5666-spr17-javatrix-candy#1]
the one parameter constructor

**Comment by matts-dev** [comment]
Working on this.

**Comment by matts-dev** [comment]
within the pull request

**Comment by matts-dev** [comment]
What needs changing on this?

**Comment by matts-dev** [comment]
@andersonmc2  Did this constructor need changing?

**Comment by andersonmc2** [comment]
Sorry, didn't see your comments, I added functionality to this constructor to set the rows and cols fields.
