### ISSUE TITLE
Could someone review the 1d constructor?

### ISSUE THREAD

**Issue by matts-dev** [JaysGitLab/cs5666-spr17-javatrix-candy#52]
I haven't taken linear, I wanted to make sure I implemented it correctly.

**Comment by andersonmc2** [comment]
On it

**Comment by andersonmc2** [comment]
Okay so if I'm understanding this right, the array is packed by columns meaning its length / m is the number of cols for the matrix (like you've set up). However, it looks like your for loop is backwards. I haven't run it yet, but it looks like its filling the matrix by row, when it should be filled by column, if I'm correctly understanding the "packed by columns" sentence. I could be wrong on this so let me know if you agree/disagree.

For example: the array [1,2,3,4,5,6] and m = 3 should give a matrix: 
[1  4
 2  5
 3  6]

where it currently generates:
[1  2
3   4
5   6]

does that sound right?

**Comment by matts-dev** [comment]
Okay, thanks for looking at it. I will change the constructor and the test to produce
 [1 4
2 5
3 6]
style matrices.

**Comment by matts-dev** [comment]
fixed it!
